// Code generated by MockGen. DO NOT EDIT.
// Manual mock for network functionality

// Package mock is a generated GoMock package.
package mock

import (
	"reflect"

	"github.com/aliyun/wuying-agentbay-sdk/golang/pkg/agentbay"
	"github.com/golang/mock/gomock"
)

// MockNetworkInterface is a mock of NetworkInterface interface.
type MockNetworkInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkInterfaceMockRecorder
}

// MockNetworkInterfaceMockRecorder is the mock recorder for MockNetworkInterface.
type MockNetworkInterfaceMockRecorder struct {
	mock *MockNetworkInterface
}

// NewMockNetworkInterface creates a new mock instance.
func NewMockNetworkInterface(ctrl *gomock.Controller) *MockNetworkInterface {
	mock := &MockNetworkInterface{ctrl: ctrl}
	mock.recorder = &MockNetworkInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkInterface) EXPECT() *MockNetworkInterfaceMockRecorder {
	return m.recorder
}

// CreateNetwork mocks base method.
func (m *MockNetworkInterface) CreateNetwork(networkID *string) (*agentbay.CreateNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", networkID)
	ret0, _ := ret[0].(*agentbay.CreateNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockNetworkInterfaceMockRecorder) CreateNetwork(networkID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockNetworkInterface)(nil).CreateNetwork), networkID)
}

// DescribeNetwork mocks base method.
func (m *MockNetworkInterface) DescribeNetwork(networkID string) (*agentbay.DescribeNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeNetwork", networkID)
	ret0, _ := ret[0].(*agentbay.DescribeNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeNetwork indicates an expected call of DescribeNetwork.
func (mr *MockNetworkInterfaceMockRecorder) DescribeNetwork(networkID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNetwork", reflect.TypeOf((*MockNetworkInterface)(nil).DescribeNetwork), networkID)
}
